name: sante
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Icônes iOS
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.17.3

  # Localisation
  flutter_localizations:
    sdk: flutter

  # Génération PDF
  pdf: ^3.10.4
  printing: ^5.12.0

  # Envoi d'emails
  mailer: ^6.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatar.jpeg
