// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHpX4Ay_bwaV6NDWkJWSeHZW4avxjKv6s',
    appId: '1:525423573907:web:6be1152c3d0d9d80164666',
    messagingSenderId: '525423573907',
    projectId: 'health-6a922',
    authDomain: 'health-6a922.firebaseapp.com',
    storageBucket: 'health-6a922.firebasestorage.app',
    measurementId: 'G-KJ866F9WX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoIFhaxWrrA7RqLx4xZ8P-o3j3wQxXkGc',
    appId: '1:525423573907:android:5cec0cbdb47b7389164666',
    messagingSenderId: '525423573907',
    projectId: 'health-6a922',
    storageBucket: 'health-6a922.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLByaSshkhQAme6507JC8Q1njoY_N5-XY',
    appId: '1:525423573907:ios:fb04e5569e3127e6164666',
    messagingSenderId: '525423573907',
    projectId: 'health-6a922',
    storageBucket: 'health-6a922.firebasestorage.app',
    iosBundleId: 'com.example.sante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLByaSshkhQAme6507JC8Q1njoY_N5-XY',
    appId: '1:525423573907:ios:fb04e5569e3127e6164666',
    messagingSenderId: '525423573907',
    projectId: 'health-6a922',
    storageBucket: 'health-6a922.firebasestorage.app',
    iosBundleId: 'com.example.sante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHpX4Ay_bwaV6NDWkJWSeHZW4avxjKv6s',
    appId: '1:525423573907:web:d38b240ed7de4780164666',
    messagingSenderId: '525423573907',
    projectId: 'health-6a922',
    authDomain: 'health-6a922.firebaseapp.com',
    storageBucket: 'health-6a922.firebasestorage.app',
    measurementId: 'G-QYJWNHKLXJ',
  );
}
